[dependencies.wasm-project]
default-features = false
features = []
package = "solochain-template-runtime"
path = "/home/neurosx/NEWsubstrateprojects/my-custom-solochain/runtime"

[lib]
crate-type = ["cdylib"]
name = "solochain_template_runtime"

[package]
edition = "2021"
name = "solochain-template-runtime-blob"
version = "1.0.0"

[profile.dev]
panic = "abort"

[profile.production]
codegen-units = 1
inherits = "release"
lto = "fat"

[profile.release]
lto = "thin"
panic = "abort"

[workspace]
resolver = "2"
